### ISSUE TITLE
Support multiple series designated by a string field in line charts

### ISSUE THREAD

**Issue by moonranger** [marianogappa/chart#14]
For example, with the following data

```
foo	2017-06-23	1
foo	2017-06-24	2
foo	2017-06-25	3
foo	2017-06-26	4
foo	2017-06-27	5
foo	2017-06-28	6
bar	2017-06-23	9
bar	2017-06-24	8
bar	2017-06-25	7
bar	2017-06-26	6
bar	2017-06-27	5
bar	2017-06-28	4
```

`chart line --date-format 2006-01-02` can generate a line chart with 2 series, `foo` and `bar`.

**Comment by marianogappa** [comment]
This is a little trickier than I thought. There are (a) two types of line charts and (b) two main ways of supplying the data.

(a) Types of line charts:
- Categorical: the x-axis is composed of discrete values (strings)
- Continuous: the x-axis is composed of floats or times and follow a scale

(b) Main ways of supplying the data:
- All series per row: each row of input contains an x-value and all y-values of all line series
- One data point per row: each row of input contains an x-value and an y-value

At the moment, `chart` will attempt to make a continuous line chart if possible (i.e. if there are at least 2 float fields or 1 float and 1 time field per row), and fallback to a categorical line chart otherwise, assuming there are at least 1 string field and 1 float field.

It may be tricky to infer the right desired configuration without command line arguments. Can we discuss this together this week?

**Comment by moonranger** [comment]
I'm not sure I know enough about the implementation to be able to provide useful input but would be happy to have a chat ;-)

Just another crazy idea: so instead of trying to put multiple series into a single chart, we can instead generate multiple charts on a single HTML page, and use the string field's value as the title. It should work for all types of charts. You basically group the data by that string field and generate individual charts and put them all in one page (kinda like a dashboard). I think it's especially useful in my use case I showed you the other day. Will leave it to you to judge whether it's a good idea or not. 😛

**Comment by marianogappa** [comment]
@moonranger I've implemented "denormalised scatter multi series line charts" (i.e. line charts with multiple series where the x-axis is continuous as opposed to categorical and each line of input corresponds to a single data point) in this commit: https://github.com/marianogappa/chart/commit/de99b4d0d0c65acf80f7bda7da40bfb5cb29d778

Your example now works. I've added an example in [the cheatsheet](https://marianogappa.github.io/chart/) (denormalised-scatter-line.csv)
; can you `go get -u github.com/marianogappa/chart` and test it with your actual use case and let me know what you think?

It's still lacking proper legend support. I'll keep the issue open as I get on to that.

Regarding your crazy idea, I think it's out of the scope of what chart does, but I'm more than happy to explore the idea of building something on top of chart say in a hackathon :P disposable dashboards is an intriguing idea.

**Comment by marianogappa** [comment]
@moonranger added automatic legend support. Can you please update your binary and see if it works properly for you? You can also check the cheatsheet examples: https://marianogappa.github.io/chart/

I will implement optional legend overriding as part of the separate issue you created https://github.com/marianogappa/chart/issues/17.

**Comment by moonranger** [comment]
@marianogappa I've updated my binary and used it once. It generated a graph I expected.

There was only one small issue:  `chart` used the same color for different legends because there were a lot of lines.

Will create a separate issue for adding more colors.

**Comment by marianogappa** [comment]
@moonranger thanks! Closing this ticket.
