### ISSUE TITLE
Line charts not displaying tooltips

### ISSUE THREAD

**Issue by kmatt** [marianogappa/chart#5]
Bar and pie charts show data points on mouseover, but line charts do not seem to be. This is seen locally and on https://marianogappa.github.io/chart/

Tooltips are referenced at https://github.com/marianogappa/chart/blob/master/line.go#L107

Are line chart tooltips currently supported?

**Comment by marianogappa** [comment]
I haven't spent much time on tooltips yet; they may be inconsistent between chart types or broken. We just haven't had the use case yet, and generally coding things we don't test leads to buggy code.

I'm glad to see that you're trying chart! Can you describe your use case? What would you expect exactly? I might get to work on it this weekend.

Cheers!

**Comment by kmatt** [comment]
> Can you describe your use case? 

Simple timeseries trending, usually the output of an Awk script that counts things on a time or date stamp:

    2016-01-01, 100
    2016-01-02, 105
    2016-01-03, 95
 
This utility is a bit simpler to use than gnuplot and R/ggplot, and the tooltips in the chart formats where supported are useful.  I'm looking at line.go to see if I can figure out how to port them from bar.go or scatter.go

**Comment by marianogappa** [comment]
@kmatt my bad; the lack of tooltips was a bug. Fixed in the above commit.

**This new release has the fix on it**
https://github.com/marianogappa/chart/releases/tag/v1.0.2

**Tooltips now appear**
https://marianogappa.github.io/chart/

Regardless of the bug being fixed, is the feature satisfying your use case? Thanks in advance for the review. Let me know if you find any other use cases chart is not enabling for you.

If approved, please close the Issue. I will close after some time of inactivity.

**Comment by kmatt** [comment]
Yes, those work well!
