### ISSUE TITLE
All line charts are zero based?

### ISSUE THREAD

**Issue by kmatt** [marianogappa/chart#6]
If I render a line chart with or without the -zero-based argument, the y-axis is always anchored at zero. Is the default y-axis supposed to be based on the minimum value?

**Comment by marianogappa** [comment]
Thank you.

**The `--zero-based` option was only partially supported by this commit:**
https://github.com/marianogappa/chart/commit/6d931b2e1056773aee348d88c9a84b0fd14ffac3

**This release has --zero-based support for all charts**
https://github.com/marianogappa/chart/releases/tag/v1.0.3
(or just `go get -u`)

FYI `--zero-based` was actually implemented for a kind of line charts, but there are 2 underlying types of line charts:
- "discrete" line charts
- "scatter" line charts
The difference is that "discrete" line charts are not scaled, because the x-axis values are strings.

Let me know if it works for you. Thank you for your reviews! Please close if solved.

**Comment by kmatt** [comment]
Works as expected!
